### ISSUE TITLE
basic example broken: requests parameter not in data_message_reader

### ISSUE THREAD

**Issue by gvankeerberghen** [mwilliamson/sdmx.py#1]
Hi,

I've downloaded your package from pypi to parse an sdmx generic data message. I tried running your example but it crashes with the below message.

I've looked into the code and from what I understand data_message_reader needs an input _requests_ that is directly passed to a DsdFetcher object (line 181 in dataset.py). There is no such input in your example and the ones I've tried to guess didn't work.

Could you help me understand what I should input as _request_? Btw, this prevents your "Hello, world!" example from running. 

Thanks for your help.
# Error Message

AttributeError                            Traceback (most recent call last)
<ipython-input-6-13482a2e7c0e> in <module>()
     32                 print zip(dimension_names, row)
     33 
---> 34 main()

<ipython-input-6-13482a2e7c0e> in main()
      7             )
      8 
----> 9             _print_values(data_set_reader)
     10 
     11 

<ipython-input-6-13482a2e7c0e> in _print_values(dataset_reader)
     11 
     12 def _print_values(dataset_reader):
---> 13     for dataset in dataset_reader.datasets():
     14         key_family = dataset.key_family()
     15         name = key_family.name(lang="en")

/Users/Guillaume/anaconda/lib/python2.7/site-packages/sdmx/dataset.py in datasets(self)
     55             return iteration.map(
     56                 self._read_dataset_element,
---> 57                 parser.get_dataset_elements(self._root),
     58             )
     59 

/Users/Guillaume/anaconda/lib/python2.7/site-packages/sdmx/dataset.py in _read_dataset_element(self, element)
     59 
     60         def _read_dataset_element(self, element):
---> 61             return DatasetReader(element, self._key_family(element))
     62 
     63         def _key_family(self, dataset_element):

/Users/Guillaume/anaconda/lib/python2.7/site-packages/sdmx/dataset.py in _key_family(self, dataset_element)
     62 
     63         def _key_family(self, dataset_element):
---> 64             dsd_reader = self._dsd_reader(dataset_element)
     65             return KeyFamily(
     66                 parser.key_family_for_dataset(dataset_element, dsd_reader),

/Users/Guillaume/anaconda/lib/python2.7/site-packages/sdmx/dataset.py in _dsd_reader(self, dataset_element)
     73                 return default_dsd_reader
     74             else:
---> 75                 return self._dsd_fetcher.fetch(key_family_uri)
     76 
     77     class DatasetReader(object):

/Users/Guillaume/anaconda/lib/python2.7/site-packages/sdmx/dataset.py in fetch(self, url)
     18     def fetch(self, url):
     19         if url not in self._cache:
---> 20             response = self._requests.get(url)
     21             fileobj = io.BytesIO()
     22             for buf in response.iter_content(16 \* 1024):

AttributeError: 'NoneType' object has no attribute 'get'

**Comment by mwilliamson** [comment]
Ah, I suspect that the expectation is that `requests` is the `requests` module. Given that it looks like that's not being initialised correctly if not explicitly set, then whether or not the example works will depend on what sort of file you're trying the example with.

I'll see about fixing up the code to have sensible default behaviour.

**Comment by mwilliamson** [comment]
I've just uploaded 0.2.10 to PyPI. Could you give that a whirl and see if that sorts things out?

**Comment by gvankeerberghen** [comment]
Works fine now. Thanks a lot and nice job!
